package cdklabscdkverifiedpermissions

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/cdklabs/cdk-verified-permissions-go/cdklabscdkverifiedpermissions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/cdklabs/cdk-verified-permissions-go/cdklabscdkverifiedpermissions/internal"
)

// Experimental.
type Policy interface {
	awscdk.Resource
	IPolicy
	// Experimental.
	Definition() *PolicyDefinitionProperty
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	// Experimental.
	Env() *awscdk.ResourceEnvironment
	// The tree node.
	// Experimental.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// The unique ID of the new or updated policy.
	// Experimental.
	PolicyId() *string
	// Experimental.
	PolicyStoreId() *string
	// The type of the policy.
	//
	// This is one of the following values: Static or TemplateLinked.
	// Experimental.
	PolicyType() PolicyType
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
}

// The jsii proxy struct for Policy
type jsiiProxy_Policy struct {
	internal.Type__awscdkResource
	jsiiProxy_IPolicy
}

func (j *jsiiProxy_Policy) Definition() *PolicyDefinitionProperty {
	var returns *PolicyDefinitionProperty
	_jsii_.Get(
		j,
		"definition",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Policy) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Policy) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Policy) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Policy) PolicyId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"policyId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Policy) PolicyStoreId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"policyStoreId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Policy) PolicyType() PolicyType {
	var returns PolicyType
	_jsii_.Get(
		j,
		"policyType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Policy) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Experimental.
func NewPolicy(scope constructs.Construct, id *string, props *PolicyProps) Policy {
	_init_.Initialize()

	if err := validateNewPolicyParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_Policy{}

	_jsii_.Create(
		"@cdklabs/cdk-verified-permissions.Policy",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewPolicy_Override(p Policy, scope constructs.Construct, id *string, props *PolicyProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@cdklabs/cdk-verified-permissions.Policy",
		[]interface{}{scope, id, props},
		p,
	)
}

// Create a policy based on a file containing a cedar policy.
//
// Best practice would be
// for the file name to end in `.cedar` but this is not required. Policy is parsed for valid
// syntax but not validated against schema. In order to validate against schema, use
// `PolicyStore.addPoliciesFromPath()`
// Experimental.
func Policy_FromFile(scope constructs.Construct, defaultPolicyId *string, props *StaticPolicyFromFileProps) *[]Policy {
	_init_.Initialize()

	if err := validatePolicy_FromFileParameters(scope, defaultPolicyId, props); err != nil {
		panic(err)
	}
	var returns *[]Policy

	_jsii_.StaticInvoke(
		"@cdklabs/cdk-verified-permissions.Policy",
		"fromFile",
		[]interface{}{scope, defaultPolicyId, props},
		&returns,
	)

	return returns
}

// Import a Policy construct from attributes.
// Experimental.
func Policy_FromPolicyAttributes(scope constructs.Construct, id *string, attrs *PolicyAttributes) IPolicy {
	_init_.Initialize()

	if err := validatePolicy_FromPolicyAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IPolicy

	_jsii_.StaticInvoke(
		"@cdklabs/cdk-verified-permissions.Policy",
		"fromPolicyAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Import a policy into the CDK using its id.
// Experimental.
func Policy_FromPolicyId(scope constructs.Construct, id *string, policyId *string) IPolicy {
	_init_.Initialize()

	if err := validatePolicy_FromPolicyIdParameters(scope, id, policyId); err != nil {
		panic(err)
	}
	var returns IPolicy

	_jsii_.StaticInvoke(
		"@cdklabs/cdk-verified-permissions.Policy",
		"fromPolicyId",
		[]interface{}{scope, id, policyId},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func Policy_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validatePolicy_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/cdk-verified-permissions.Policy",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Experimental.
func Policy_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validatePolicy_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/cdk-verified-permissions.Policy",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func Policy_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validatePolicy_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/cdk-verified-permissions.Policy",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_Policy) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := p.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		p,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (p *jsiiProxy_Policy) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		p,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (p *jsiiProxy_Policy) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := p.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		p,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_Policy) GetResourceNameAttribute(nameAttr *string) *string {
	if err := p.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		p,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_Policy) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		p,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

