package cdklabscdkverifiedpermissions

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/cdklabs/cdk-verified-permissions-go/cdklabscdkverifiedpermissions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/cdklabs/cdk-verified-permissions-go/cdklabscdkverifiedpermissions/internal"
)

// Experimental.
type PolicyTemplate interface {
	awscdk.Resource
	IPolicyTemplate
	// Description of the policy template.
	// Experimental.
	Description() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed in a Stack (those created by
	// creating new class instances like `new Role()`, `new Bucket()`, etc.), this
	// is always the same as the environment of the stack they belong to.
	//
	// For referenced resources (those obtained from referencing methods like
	// `Role.fromRoleArn()`, `Bucket.fromBucketName()`, etc.), they might be
	// different than the stack they were imported into.
	// Experimental.
	Env() *interfaces.ResourceEnvironment
	// The tree node.
	// Experimental.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// The Policy store that contains the template.
	// Experimental.
	PolicyStore() IPolicyStore
	// The ID of the policy template.
	// Experimental.
	PolicyTemplateId() *string
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// The statement of the policy template.
	// Experimental.
	Statement() *string
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
}

// The jsii proxy struct for PolicyTemplate
type jsiiProxy_PolicyTemplate struct {
	internal.Type__awscdkResource
	jsiiProxy_IPolicyTemplate
}

func (j *jsiiProxy_PolicyTemplate) Description() *string {
	var returns *string
	_jsii_.Get(
		j,
		"description",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PolicyTemplate) Env() *interfaces.ResourceEnvironment {
	var returns *interfaces.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PolicyTemplate) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PolicyTemplate) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PolicyTemplate) PolicyStore() IPolicyStore {
	var returns IPolicyStore
	_jsii_.Get(
		j,
		"policyStore",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PolicyTemplate) PolicyTemplateId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"policyTemplateId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PolicyTemplate) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PolicyTemplate) Statement() *string {
	var returns *string
	_jsii_.Get(
		j,
		"statement",
		&returns,
	)
	return returns
}


// Experimental.
func NewPolicyTemplate(scope constructs.Construct, id *string, props *PolicyTemplateProps) PolicyTemplate {
	_init_.Initialize()

	if err := validateNewPolicyTemplateParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_PolicyTemplate{}

	_jsii_.Create(
		"@cdklabs/cdk-verified-permissions.PolicyTemplate",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewPolicyTemplate_Override(p PolicyTemplate, scope constructs.Construct, id *string, props *PolicyTemplateProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@cdklabs/cdk-verified-permissions.PolicyTemplate",
		[]interface{}{scope, id, props},
		p,
	)
}

// Experimental.
func PolicyTemplate_FromFile(scope constructs.Construct, id *string, props *TemplateFromFileProps) PolicyTemplate {
	_init_.Initialize()

	if err := validatePolicyTemplate_FromFileParameters(scope, id, props); err != nil {
		panic(err)
	}
	var returns PolicyTemplate

	_jsii_.StaticInvoke(
		"@cdklabs/cdk-verified-permissions.PolicyTemplate",
		"fromFile",
		[]interface{}{scope, id, props},
		&returns,
	)

	return returns
}

// Creates a PolicyTemplate construct that represents an external Policy Template.
// Experimental.
func PolicyTemplate_FromPolicyTemplateAttributes(scope constructs.Construct, id *string, attrs *PolicyTemplateAttributes) IPolicyTemplate {
	_init_.Initialize()

	if err := validatePolicyTemplate_FromPolicyTemplateAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IPolicyTemplate

	_jsii_.StaticInvoke(
		"@cdklabs/cdk-verified-permissions.PolicyTemplate",
		"fromPolicyTemplateAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Create a PolicyTemplate construct that represents an external policy template via policy template id.
// Experimental.
func PolicyTemplate_FromPolicyTemplateId(scope constructs.Construct, id *string, policyTemplateId *string) IPolicyTemplate {
	_init_.Initialize()

	if err := validatePolicyTemplate_FromPolicyTemplateIdParameters(scope, id, policyTemplateId); err != nil {
		panic(err)
	}
	var returns IPolicyTemplate

	_jsii_.StaticInvoke(
		"@cdklabs/cdk-verified-permissions.PolicyTemplate",
		"fromPolicyTemplateId",
		[]interface{}{scope, id, policyTemplateId},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func PolicyTemplate_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validatePolicyTemplate_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/cdk-verified-permissions.PolicyTemplate",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Experimental.
func PolicyTemplate_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validatePolicyTemplate_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/cdk-verified-permissions.PolicyTemplate",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func PolicyTemplate_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validatePolicyTemplate_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdklabs/cdk-verified-permissions.PolicyTemplate",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PolicyTemplate) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := p.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		p,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (p *jsiiProxy_PolicyTemplate) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		p,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PolicyTemplate) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := p.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		p,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PolicyTemplate) GetResourceNameAttribute(nameAttr *string) *string {
	if err := p.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		p,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PolicyTemplate) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		p,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

